### ISSUE TITLE
Feel free to use my 2018 survey work

### ISSUE THREAD

**Issue by LawrenceHecht** [jeremydaly/serverless-community-survey-2020#1]
The raw data and tabulated results are here: https://docs.google.com/spreadsheets/d/1OnArfd4nPGUbuJZMR4P38E4ODfrriIEa_9sbvQmp3KI/edit#gid=113874481

**Comment by BDQ** [comment]
@LawrenceHecht question around the percentage of production workloads are interesting for sure, so just +1 ing those.
