### ISSUE TITLE
Question by question comments

### ISSUE THREAD

**Issue by LawrenceHecht** [jeremydaly/serverless-community-survey-2020#2]
1. Don't start the questionnaire off with this boring but important question. An alternative question could be: "Which of the following cloud platforms does your organization use at least in part for production applications that have serverless components in them? (check all that apply)"
2. Generic cloud experience is not critical. If the wording is changed to be about experience with serverless in production, then that could be interesting. 
3. 
4. I assume we are trying to show that many people took the leap straight to serverless and/or that it takes a real cloud expert to use it. Wording could be improved.
5. 
6. Why is this necessary to ask? Are you trying to see which container platforms/services are being used in conjunction with a FaaS?
7. If you add a list of 8-12 service categories, that could work. That avoids dealing with too many products.
8.
9. I'm interested in if people are using point solutions, something bundled with a larger monitoring solution, and/or what is offered by their cloud provider.
10. I would remove this and/or try to add more choices. The challenge is that a lot o solutions are marketed more broadly as dealing with containers and/or microservices.
11. 
12. Not important. You can take this out.
13. Touchy subject. Why not just ask, "Which data stores do you integrate with your serverless applications?" 
14.
15. I can imagine why you're interested in this, but I also think you already know the answer. I would remove the question.
16. Clarify this to be about either building a new or continue working on an existing serverless app.
17. Not an important quesiton
18. 
19. Interesting subject. As is, the question needs work.
20. Would this affect people that are not AWS customers?
21. Would this affect people that are not AWS customers?
22. Do you want to ask about the organization or the person? I would make the list longer. 
23. ""
24. Get rid of question -- I like the last two choices, but they are not mutually exclusive.
25. 
26. Change to "Which category most closely defines your job role?" and make this close-ended. Also, put it before or after all the "organization" questions.
27. Ask this and a question about email address at the very end.
28. Good!
29. 
30. I'm not sure the data will be that interesting. The subject is worthwhile if it can be reworded.
31.

**Comment by jeremydaly** [comment]
Thanks for the great feedback, Lawrence! I know some of the questions are a bit vendor specific, but perhaps some of that can be handled by skip logic. Also, the question order hasn't been established yet, so I take your point on that.

Regarding Q12, I do want to get a sense of where people are learning about serverless offerings. This goes to the broader question about cloud training and education that I'm trying to address in Q15. I agree that this isn't the right way to ask the question, but I'd like to get some sort of answer to this. Maybe something like: "How would you describe your current cloud provider's quality and quantity of training materials/documentation?" Maybe this needs to be multiple questions, but I think there's a way to get valuable info here.

Q17 is not how I would want to ask it, but I'm curious to get feedback on multicloud and how companies are approaching it. I know from other studies that K8s is popular for this reason, but I'm curious if companies are looking for agnostic portability, full parity, platform diversity, or the availability of differentiated services.

A few points you make about the individual versus the company are interesting. I was struggling with this on just about every question. I think understanding the individual's experience, perceptions, and usage versus that of the company they work for is important. Perhaps the survey could be divided into sections that address personal versus corporate?

**Comment by LawrenceHecht** [comment]
Do you know what survey software you plan on using? Or do you plan to hand code it? I ask this specifically because you mentioned skip logic.

The survey can be divided into sections re: corporate vs personal. Alternatively, you can use **bold** or CAPS to make sure people know what the focus is. 

Why don't you ping me next week and I'll review again.
